<a href="https://colab.research.google.com/github/StepanPro999636/bool_bool/blob/main/homework/homework_lesson2_Lazarenko_Stephan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#Задание 1

arr = np.arange(1+2,30+1)
print(np.where((arr)%3==0))
#Я не знаю, что мне с этим where делать. Он поломан

(array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27]),)


In [ ]:
#Задание 2

mtrx = np.arange(1,30+1).reshape(6,5)
print("Изначальная матрица 6x5:\n",mtrx,"\n")
mtrx = mtrx.reshape(5,6)
print("Изменёная матрица 5x6:\n",mtrx,"\n")
print("Сумма по столбцам:")
for i in range(np.shape(mtrx)[1]): print(f"{sum(mtrx[:,i])}",end=" ")

"""код проходит по матице mtrx столько же раз, сколько в ней столбцов. получаю кол-во столбцов: shape(mtrx); создаётся кортеж со значениями (строки, столбцы); количество столбцов имеет индекс i,
его я и использую в качестве счётчика для цикла for, который теперь при каждой итерации записывает в i индекс итерируемого столбца. далее просто получаем массив значений итерируемого столбца
через mtrx[:,i] и суммируем их функцией sum()"""

Изначальная матрица 6x5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]] 

Изменёная матрица 5x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]] 

Сумма по столбцам:
65 70 75 80 85 90 

'код проходит по матице mtrx столько же раз, сколько в ней столбцов. получаю кол-во столбцов: shape(mtrx); создаётся кортеж со значениями (строки, столбцы); количество столбцов имеет индекс i,\nего я и использую в качестве счётчика для цикла for, который теперь при каждой итерации записывает в i индекс итерируемого столбца. далее просто получаем массив значений итерируемого столбца\nчерез mtrx[:,i] и суммируем их функцией sum()'

In [ ]:
#Задание 3

lst1 = np.random.randint(1,10+1,size=(1,10))
lst2 = np.random.randint(1,10+1,size=(1,10))
print(f"lst1 = {lst1}")
print(f"lst2 = {lst2}")
print(f"lst1 * lst2 = {lst1*lst2}")


lst1 = [[6 7 9 5 8 3 4 4 7 8]]
lst2 = [[ 3  6 10  4  5  2  1  5  9  4]]
lst1 * lst2 = [[18 42 90 20 40  6  4 20 63 32]]
